package com.tencent.devops.pojo

const val PARAM_SEPARATOR = ","

// not use
const val DEVOPS_GIT_URLS = "DEVOPS_GIT_URLS"
const val DEVOPS_GIT_HEAD_COMMITS = "DEVOPS_GIT_HEAD_COMMITS"
const val DEVOPS_GIT_BRANCHES = "DEVOPS_GIT_BRANCHES"
const val DEVOPS_GIT_CODE_PATHS = "DEVOPS_GIT_CODE_PATHS"

const val DEVOPS_GIT_REPO_URL = "DEVOPS_GIT_REPO_URL"
const val DEVOPS_GIT_REPO_NAME = "DEVOPS_GIT_REPO_NAME"
const val DEVOPS_GIT_REPO_ALIAS_NAME = "DEVOPS_GIT_REPO_ALIAS_NAME"
const val DEVOPS_GIT_REPO_BRANCH = "DEVOPS_GIT_REPO_BRANCH"
const val DEVOPS_GIT_REPO_CODE_PATH = "DEVOPS_GIT_REPO_CODE_PATH"
const val DEVOPS_GIT_REPO_LAST_COMMIT_ID = "DEVOPS_GIT_REPO_LAST_COMMIT_ID"
const val DEVOPS_GIT_REPO_HEAD_COMMIT_ID = "DEVOPS_GIT_REPO_HEAD_COMMIT_ID"
const val DEVOPS_GIT_REPO_HEAD_COMMIT_COMMENT = "DEVOPS_GIT_REPO_HEAD_COMMIT_COMMENT"
const val DEVOPS_GIT_REPO_CUR_COMMITS = "DEVOPS_GIT_REPO_COMMITS"

// use this

const val BK_CI_GIT_URLS = "BK_CI_GIT_URLS"
const val BK_CI_GIT_HEAD_COMMITS = "BK_CI_GIT_HEAD_COMMITS"
const val BK_CI_GIT_BRANCHES = "BK_CI_GIT_BRANCHES"
const val BK_CI_GIT_CODE_PATHS = "BK_CI_GIT_CODE_PATHS"

const val BK_CI_GIT_REPO_URL = "BK_CI_GIT_REPO_URL"
const val BK_CI_GIT_REPO_NAME = "BK_CI_GIT_REPO_NAME"
const val BK_CI_GIT_REPO_ALIAS_NAME = "BK_CI_GIT_REPO_ALIAS_NAME"
const val BK_CI_GIT_REPO_BRANCH = "BK_CI_GIT_REPO_BRANCH"
const val BK_CI_GIT_REPO_TAG = "BK_CI_GIT_REPO_TAG"
const val BK_CI_GIT_REPO_CODE_PATH = "BK_CI_GIT_REPO_CODE_PATH"
const val BK_CI_GIT_REPO_LAST_COMMIT_ID = "BK_CI_GIT_REPO_LAST_COMMIT_ID"
const val BK_CI_GIT_REPO_HEAD_COMMIT_ID = "BK_CI_GIT_REPO_HEAD_COMMIT_ID"
const val BK_CI_GIT_REPO_HEAD_COMMIT_COMMENT = "BK_CI_GIT_REPO_HEAD_COMMIT_COMMENT"
const val BK_CI_GIT_REPO_HEAD_COMMIT_AUTHOR = "BK_CI_GIT_REPO_HEAD_COMMIT_AUTHOR"
const val BK_CI_GIT_REPO_HEAD_COMMIT_COMMITTER = "BK_CI_GIT_REPO_HEAD_COMMIT_COMMITTER"
const val BK_CI_GIT_REPO_CUR_COMMITS = "BK_CI_GIT_REPO_COMMITS"

// mr专用
const val BK_CI_GIT_REPO_MR_TARGET_HEAD_COMMIT_ID = "BK_CI_GIT_REPO_MR_TARGET_HEAD_COMMIT_ID"
