package com.tencent.bk.devops.git.core.pojo

data class GitMetricsInfo(
    val atomCode: String,
    val projectId: String,
    val pipelineId: String,
    val buildId: String,
    val taskId: String,
    val scmType: String,
    val url: String,
    val projectName: String,
    val startTime: String,
    val endTime: String,
    val costTime: Long,
    val prepareCostTime: Long,
    val initCostTime: Long,
    val submoduleCostTime: Long,
    val lfsCostTime: Long,
    val fetchCostTime: Long,
    val checkoutCostTime: Long,
    val logCostTime: Long,
    val authCostTime: Long,
    val fetchStrategy: String,
    val errorType: Int? = 0,
    val errorCode: Int? = null,
    val errorMessage: String? = null,
    val status: String? = null,
    val bkRepoDownloadCostTime: Long,
    val bkRepoDownloadResult: String,
    val errorInfo: String
)
