# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: deploy CI jar to OSS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set up GPG
        run: |
          echo ${{ github.workspace }}
          # gpg init
          mkdir ~/.gnupg && echo use-agent >> ~/.gnupg/gpg.conf
          echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
          echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
          echo ${SIGNING_KEY} | awk '{gsub(/\\n/,"\n")}1'| gpg --dearmor > ${{ github.workspace }}/secretKeyRingFile.gpg
          gpg --import  --pinentry-mode loopback --batch --passphrase '${SIGNING_PASSWORD}' ${{ github.workspace }}/secretKeyRingFile.gpg
          ls -al ${{ github.workspace }}
          ls -al ~/.gnupg/
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Gradle Build
        env:
          build_mavenRepoDeployUrl: "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
          build_mavenRepoUsername: ${{ secrets.SONATYPE_USERNAME }}
          build_mavenRepoPassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          core_version=${GITHUB_REF##*/v}
          echo "core_version=${core_version}"
          chmod +x ./gradlew
          ./gradlew :git-checkout-credential:clean shadowJar
          ./gradlew publish -Dcore_version=${core_version} \
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
          -Psigning.password='${{ secrets.SIGNING_PASSWORD }}' \
          -Psigning.secretKeyRingFile=${{ github.workspace }}/secretKeyRingFile.gpg \
          -DmavenRepoUrl="http://maven.aliyun.com/nexus/content/groups/public/"
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
      - name: Clean Up
        if: ${{ always() }}
        run: |
          rm -rf ~/.gnupg
